# Site settings
title: "小黄"
email: jacob@jacobtomlinson.co.uk
description: "A dark blog theme for Jekyll."
baseurl: ""
url: "http://carte-noire.jacobtomlinson.co.uk/"
title_description: "是程序设计，又是UI/UE设计"
title_image: "http://192.241.220.247/wp-content/uploads/2015/07/me.jpg"
google_analytics: "UA-20365477-4"
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
github_username:  HFATFAT
wordpress_link: http://192.241.220.247/
behance_link: https://www.behance.net/hfatfat
google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
stackoverflow_link: http://stackoverflow.com/users/5091920/hfatfat

# Footer
footer_left: "Theme by <i class=\"fa fa-heart\"></i> <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]

#markdown: kramdown  
